"use client";
import Link from "next/link";import { useParams } from "next/navigation";import { useState } from "react";import { ArrowLeft,ArrowRight,CheckCircle2,Save } from "lucide-react";import { pets } from "@/lib/data";
const labels=["About you","Your home","Care plan","References","Review"];
export default function Application(){const {id}=useParams<{id:string}>();const pet=pets.find(p=>p.id===id)||pets[0];const [step,setStep]=useState(0);const [done,setDone]=useState(false);const [saved,setSaved]=useState(false);if(done)return <main className="page"><div className="shell"><div className="form-card form-head"><CheckCircle2 size={58} color="#214e3d" style={{margin:"auto"}}/><h2>Application submitted.</h2><p>{pet.organization} has received your application for {pet.name}. You can follow its status in your dashboard.</p><Link href="/dashboard" className="btn btn-primary">View application status</Link></div></div></main>;
 return <main className="page"><div className="shell"><form className="form-card" onSubmit={e=>{e.preventDefault();if(step<4)setStep(step+1);else setDone(true)}}><span className="eyebrow">Adoption application · {pet.name}</span><h2>{labels[step]}</h2><p>Step {step+1} of {labels.length} · Your answers are private and can be saved anytime.</p><div className="progress"><span style={{width:`${(step+1)/5*100}%`}}/></div>
 {step===0&&<div className="form-grid"><Field label="Full name"/><Field label="Age" type="number"/><Field label="Contact number"/><Field label="Occupation"/><Field label="General address" wide/><Field label="Household size" type="number"/><Field label="Emergency contact"/></div>}
 {step===1&&<div className="form-grid"><Select label="Do you own or rent?" options={["Own","Rent","Other"]}/><Select label="Home type" options={["House","Apartment","Condo","Other"]}/><Select label="Children at home?" options={["No","Yes"]}/><Select label="Current pets?" options={["No","Yes"]}/><Field label="Describe the available space" wide/><label className="wide"><input type="checkbox" required/> Everyone in my household supports this adoption.</label></div>}
 {step===2&&<div className="form-grid"><Field label="Primary caregiver"/><Field label="Monthly pet-care budget"/><Field label="Daily exercise plan" wide/><Field label="Veterinary care plan" wide/><Field label="Travel and emergency plan" wide/><div className="notice wide">Income is not the only basis for approval. Fit also depends on experience, environment, commitment, and {pet.name}’s needs.</div></div>}
 {step===3&&<div className="form-grid"><Field label="Personal reference"/><Field label="Reference contact"/><Field label="Veterinary reference (optional)"/><Field label="Landlord reference (if applicable)"/><div className="notice wide">Optional documents may be uploaded after submission. Redact account numbers and other unrelated sensitive details.</div></div>}
 {step===4&&<div><div className="panel"><h3>Ready to send?</h3><p>Your application covers household fit, care plans, and references. You can edit any section before submitting.</p></div><label style={{display:"block",marginTop:18}}><input type="checkbox" required/> I confirm these details are accurate and agree to the privacy notice.</label></div>}
 {saved&&<p role="status" style={{color:"var(--green)"}}>Draft saved on this device.</p>}<div style={{display:"flex",justifyContent:"space-between",marginTop:28}}><div>{step>0&&<button type="button" className="btn btn-ghost" onClick={()=>setStep(step-1)}><ArrowLeft size={16}/> Back</button>}</div><div style={{display:"flex",gap:8}}><button type="button" className="btn btn-ghost" onClick={()=>setSaved(true)}><Save size={16}/> Save draft</button><button className="btn btn-primary">{step===4?"Submit application":"Continue"}<ArrowRight size={16}/></button></div></div></form></div></main>}
function Field({label,type="text",wide=false}:{label:string;type?:string;wide?:boolean}){return <div className={`field ${wide?"wide":""}`}><label>{label}</label><input className="input" type={type} required/></div>}
function Select({label,options}:{label:string;options:string[]}){return <div className="field"><label>{label}</label><select className="input">{options.map(x=><option key={x}>{x}</option>)}</select></div>}
