"use client";
/* eslint-disable react/no-unescaped-entities */
import dynamic from "next/dynamic";import Image from "next/image";import Link from "next/link";import { motion,useScroll,useTransform } from "framer-motion";import { ArrowRight,BadgeCheck,Ban,CalendarCheck,Check,FileCheck2,Heart,Home,LockKeyhole,MapPin,MessageCircle,ShieldCheck,Sparkles,UserRoundCheck } from "lucide-react";import PetCard from "@/components/PetCard";import { journeySteps,pets } from "@/lib/data";
const PetScene=dynamic(()=>import("@/components/PetScene"),{ssr:false,loading:()=> <Image src="/images/furu-hero-pets.png" alt="Four adoptable pets waiting together" fill style={{objectFit:"cover"}} priority/>});
const reveal={initial:{opacity:0,y:30},whileInView:{opacity:1,y:0},viewport:{once:true,margin:"-80px"},transition:{duration:.65}};
export default function HomePage(){const {scrollYProgress}=useScroll();const progress=useTransform(scrollYProgress,[0,1],[0,1]);return <main>
 <motion.div className="scroll-progress" style={{scaleX:progress}}/>
 <section className="hero"><div className="shell hero-grid"><motion.div className="hero-copy" initial={{opacity:0,y:22}} animate={{opacity:1,y:0}} transition={{duration:.75}}><span className="eyebrow">Every pet deserves a beginning</span><h1>A new home.<span>A new beginning.</span></h1><p className="hero-lede">Meet pets whose stories are still being written. FurU brings adopters, families, and verified rescue communities together—safely and thoughtfully.</p><div className="hero-actions"><Link href="/browse" className="btn btn-primary">Find a pet <ArrowRight size={18}/></Link><Link href="/listings/new" className="btn btn-ghost">Rehome responsibly</Link></div><div className="microcopy"><div className="avatar-stack"><span/><span/><span/></div><BadgeCheck size={16} color="#214e3d"/> Trusted by pet communities across the Philippines</div></motion.div>
 <motion.div className="hero-visual" initial={{opacity:0,scale:.94}} animate={{opacity:1,scale:1}} transition={{delay:.15,duration:.9}}><div className="scene-frame"><PetScene/></div><div className="scene-label top"><Sparkles size={17} color="#e9743f"/><span><b>Ready to meet you</b><br/>Luna & Miso</span></div><div className="scene-label bottom"><Home size={17} color="#214e3d"/><span>Safe, verified connections</span></div><span className="floating-paw paw1">🐾</span><span className="floating-paw paw2">♡</span></motion.div></div>
 <div className="shell stats"><div className="stat"><b>1,248</b><span>happy homecomings</span></div><div className="stat"><b>86</b><span>verified partners</span></div><div className="stat"><b>312</b><span>pets waiting today</span></div></div></section>

 <section className="section story" id="how-it-works"><div className="shell story-grid"><motion.div className="story-copy" {...reveal}><span className="eyebrow">From waiting to welcome</span><h2>A thoughtful path home.</h2><p>Adoption should feel hopeful, never hurried. We keep each step clear and center the animal's long-term wellbeing.</p><Link href="/browse" className="btn btn-primary">Start your journey <ArrowRight size={18}/></Link></motion.div><div className="steps">{journeySteps.map(([n,title,copy],i)=><motion.div className="step" key={n} {...reveal} transition={{duration:.55,delay:i*.08}}><span className="step-num">{n}</span><div><h3>{title}</h3><p>{copy}</p></div></motion.div>)}</div></div></section>

 <section className="section"><div className="shell"><motion.div className="section-head" {...reveal}><div><span className="eyebrow">Choose your journey</span><h2>There’s a place<br/>for you here.</h2></div><p>Whether you’re growing your family or finding the right next home for a pet, FurU supports every responsible choice.</p></motion.div><div className="journeys"><motion.article className="journey adopt" {...reveal}><span className="journey-orb"/><div><span className="eyebrow">For adopters</span><h2>I want to adopt</h2><ul><li>Create your profile</li><li>Discover compatible pets</li><li>Apply and meet safely</li></ul></div><Link href="/browse" className="btn btn-dark">Meet the pets <ArrowRight size={17}/></Link></motion.article><motion.article className="journey rehome" {...reveal} transition={{duration:.65,delay:.12}}><span className="journey-orb"/><div><span className="eyebrow">For pet guardians</span><h2>I want to rehome</h2><ul><li>Verify your account</li><li>Share the pet’s full story</li><li>Review thoughtful applicants</li></ul></div><Link href="/listings/new" className="btn btn-dark">Create a listing <ArrowRight size={17}/></Link></motion.article></div></div></section>

 <section className="section" style={{background:"#ede9df"}}><div className="shell"><motion.div className="section-head" {...reveal}><div><span className="eyebrow">Waiting to meet you</span><h2>Featured friends.</h2></div><Link href="/browse" className="btn btn-ghost">See all pets <ArrowRight size={17}/></Link></motion.div><div className="cards">{pets.slice(0,6).map((pet,i)=><motion.div key={pet.id} {...reveal} transition={{delay:(i%3)*.08}}><PetCard pet={pet}/></motion.div>)}</div></div></section>

 <section className="section"><div className="shell trust-grid"><motion.div {...reveal}><span className="eyebrow">Trust is built in</span><h2>Kind hearts.<br/>Careful checks.</h2><p>We make space for human judgment while giving everyone safer tools. Income alone never decides a match—experience, environment, commitment, and the pet’s needs all matter.</p><div className="chips"><span className="chip">Human-reviewed listings</span><span className="chip">Private documents</span><span className="chip">Approximate locations only</span></div></motion.div><motion.div className="trust-card" {...reveal}><div style={{display:"flex",justifyContent:"space-between"}}><div><span className="eyebrow">Your verification</span><h3>3 of 4 complete</h3></div><ShieldCheck size={38} color="#214e3d"/></div><div className="progress"><span/></div>{[[Check,"Email verified"],[Check,"Phone verified"],[UserRoundCheck,"Identity verified"],[MapPin,"Address review pending"]].map(([Icon,label],i)=><div className="verify-item" key={String(label)}><span className="verify-icon"><Icon size={20}/></span><span>{String(label)}</span>{i<3&&<BadgeCheck style={{marginLeft:"auto"}} size={18} color="#e9743f"/>}</div>)}</motion.div></div></section>

 <section className="section"><div className="shell safety"><div><span className="eyebrow">Safety & responsibility</span><h2>Protection at every pawprint.</h2><p>FurU prohibits pet sales disguised as adoption, abuse, fraud, unsafe transfers, illegal breeding, misleading listings, and discrimination.</p><Link href="/help" className="btn btn-dark">Read our safety guide</Link></div><div className="safety-list">{[[ShieldCheck,"Moderated listings"],[MessageCircle,"Secure messaging"],[Ban,"Report & block"],[LockKeyhole,"Private documents"],[FileCheck2,"Adoption agreements"],[CalendarCheck,"Safe meet-ups"]].map(([Icon,label])=><div className="safety-item" key={String(label)}><Icon size={18}/>{String(label)}</div>)}</div></div></section>

 <section className="shell cta"><div><span className="eyebrow" style={{color:"#fff"}}>Your new best friend is waiting</span><h2>Ready for a little more love at home?</h2><p>Browse verified profiles and take the first thoughtful step.</p></div><div><Link href="/browse" className="btn">Browse pets <Heart size={18}/></Link></div></section>
 </main>}
