"use client";
import Link from "next/link";import { useState } from "react";import { ArrowLeft,ArrowRight,Heart } from "lucide-react";
const accounts=["Individual","Animal Shelter","Rescue Organization","Veterinary Clinic","Animal Welfare Group"];
export default function SignUp(){const [step,setStep]=useState(1);const [account,setAccount]=useState("Individual");const [done,setDone]=useState(false);if(done)return <main className="page"><div className="shell"><div className="form-card form-head"><span className="logo-mark" style={{margin:"auto"}}><Heart fill="currentColor"/></span><h2>Welcome to FurU.</h2><p>Your demo account is ready. Next, build your profile and complete verification when it feels right.</p><Link href="/dashboard" className="btn btn-primary">Open dashboard</Link></div></div></main>;
 return <main className="page"><div className="shell"><form className="form-card" onSubmit={e=>{e.preventDefault();if(step<3)setStep(step+1);else{localStorage.setItem("furu-session","demo");window.dispatchEvent(new Event("furu-auth"));setDone(true)}}}><div className="form-head"><div className="logo"><span className="logo-mark"><Heart size={18} fill="currentColor"/></span>FurU</div><span className="eyebrow">Step {step} of 3</span><h2>{step===1?"How will you join?":step===2?"Tell us about you.":"Set up your account."}</h2></div><div className="progress"><span style={{width:`${step/3*100}%`}}/></div>
 {step===1&&<><div className="field"><label>Account type</label><select className="input" value={account} onChange={e=>setAccount(e.target.value)}>{accounts.map(a=><option key={a}>{a}</option>)}</select></div><div className="field" style={{marginTop:16}}><label>Primary purpose</label><select className="input"><option>Adopt a pet</option><option>Rehome a pet</option><option>Both</option><option>Represent an organization</option></select></div></>}
 {step===2&&<div className="form-grid"><div className="field"><label>{account==="Individual"?"Full name":"Organization name"}</label><input className="input" required/></div><div className="field"><label>Phone number</label><input className="input" type="tel" required/></div><div className="field wide"><label>General address</label><input className="input" placeholder="City / municipality only" required/></div>{account!=="Individual"&&<><div className="field"><label>Registration number</label><input className="input"/></div><div className="field"><label>Website or social page</label><input className="input" type="url"/></div></>}</div>}
 {step===3&&<div className="form-grid"><div className="field wide"><label>Email</label><input className="input" type="email" required/></div><div className="field"><label>Password</label><input className="input" type="password" minLength={8} required/></div><div className="field"><label>Confirm password</label><input className="input" type="password" minLength={8} required/></div><label className="wide"><input type="checkbox" required/> I agree to FurU’s terms, privacy policy, and animal welfare commitment.</label></div>}
 <div style={{display:"flex",justifyContent:"space-between",marginTop:28}}>{step>1?<button className="btn btn-ghost" type="button" onClick={()=>setStep(step-1)}><ArrowLeft size={16}/> Back</button>:<span/>}<button className="btn btn-primary">{step===3?"Create account":"Continue"}<ArrowRight size={16}/></button></div></form></div></main>}
