"use client";
/* eslint-disable @typescript-eslint/no-unused-expressions */
import { useState } from "react";import { ArrowLeft,ArrowRight,CheckCircle2,ImagePlus,Save } from "lucide-react";
const steps=["Basics","Personality","Health","Home fit","Photos & review"];
export default function NewListing(){const [step,setStep]=useState(0);const [done,setDone]=useState(false);const [saved,setSaved]=useState(false);if(done)return <main className="page"><div className="shell"><div className="form-card form-head"><CheckCircle2 size={58} color="#214e3d" style={{margin:"auto"}}/><h2>Listing sent for review.</h2><p>Our moderation team will check the profile for safety, completeness, and welfare standards.</p></div></div></main>;return <main className="page"><div className="shell"><form className="form-card" onSubmit={e=>{e.preventDefault();step<4?setStep(step+1):setDone(true)}}><span className="eyebrow">Create a pet listing</span><h2>{steps[step]}</h2><p>Step {step+1} of 5 · Private addresses and sensitive documents are never shown publicly.</p><div className="progress"><span style={{width:`${(step+1)*20}%`}}/></div>
 {step===0&&<div className="form-grid"><F l="Pet name"/><S l="Animal type" o={["Dog","Cat","Rabbit","Other"]}/><F l="Breed"/><S l="Sex" o={["Female","Male","Unknown"]}/><F l="Age"/><S l="Size" o={["Small","Medium","Large"]}/><F l="General location" wide/><F l="Reason for rehoming" wide/></div>}
 {step===1&&<div className="form-grid"><F l="Personality" wide/><S l="Energy level" o={["Low","Moderate","High"]}/><S l="Training status" o={["Not started","In training","Trained"]}/><F l="Behavior and routines" wide/><F l="Favorite things" wide/></div>}
 {step===2&&<div className="form-grid"><S l="Vaccination status" o={["Up to date","In progress","Unknown"]}/><S l="Spayed / neutered" o={["Yes","No","Unknown"]}/><F l="Medical conditions" wide/><F l="Medications or allergies" wide/><F l="Veterinary clinic" wide/><div className="notice wide">Medical records are stored privately and available only to authorized reviewers and the selected adopter.</div></div>}
 {step===3&&<div className="form-grid"><S l="Good with children" o={["Yes","No","Unknown"]}/><S l="Good with cats" o={["Yes","No","Unknown"]}/><S l="Good with dogs" o={["Yes","No","Unknown"]}/><S l="Adoption urgency" o={["Standard","Soon","Urgent"]}/><F l="Preferred adopter" wide/><F l="Required home environment" wide/></div>}
 {step===4&&<div><div className="panel" style={{textAlign:"center",borderStyle:"dashed"}}><ImagePlus size={36} style={{margin:"auto"}}/><h3>Add at least 3 photos</h3><p>Use bright, recent images that clearly show the pet. JPG, PNG, or WebP · 8 MB each.</p><input type="file" accept="image/jpeg,image/png,image/webp" multiple required/></div><label style={{display:"block",marginTop:18}}><input type="checkbox" required/> I confirm this is an adoption or responsible rehoming listing—not a sale.</label></div>}
 {saved&&<p role="status" style={{color:"var(--green)"}}>Draft saved locally.</p>}<div style={{display:"flex",justifyContent:"space-between",marginTop:28}}>{step>0?<button type="button" className="btn btn-ghost" onClick={()=>setStep(step-1)}><ArrowLeft size={16}/> Back</button>:<span/>}<div style={{display:"flex",gap:8}}><button type="button" className="btn btn-ghost" onClick={()=>setSaved(true)}><Save size={16}/> Save draft</button><button className="btn btn-primary">{step===4?"Submit for review":"Continue"}<ArrowRight size={16}/></button></div></div></form></div></main>}
function F({l,wide=false}:{l:string;wide?:boolean}){return <div className={`field ${wide?"wide":""}`}><label>{l}</label><input className="input" required/></div>}function S({l,o}:{l:string;o:string[]}){return <div className="field"><label>{l}</label><select className="input">{o.map(x=><option key={x}>{x}</option>)}</select></div>}
