"use client";
import { Canvas, useFrame } from "@react-three/fiber";import { ContactShadows,Float,OrbitControls } from "@react-three/drei";import { useRef } from "react";import type { Group } from "three";
function Animal({kind,position,color}:{kind:"dog"|"cat";position:[number,number,number];color:string}){const ref=useRef<Group>(null);useFrame(({clock,pointer})=>{if(!ref.current)return;ref.current.rotation.y=pointer.x*.12;ref.current.rotation.x=Math.sin(clock.elapsedTime*1.5)*.015;ref.current.position.y=position[1]+Math.sin(clock.elapsedTime*2+(kind==="cat"?2:0))*.025});const cat=kind==="cat";return <group ref={ref} position={position} scale={cat?.82:1}>
 <mesh position={[0,.15,0]} scale={[.78,.9,.65]}><sphereGeometry args={[1,32,24]}/><meshStandardMaterial color={color} roughness={.82}/></mesh>
 <mesh position={[0,1.2,.05]}><sphereGeometry args={[.72,32,24]}/><meshStandardMaterial color={color}/></mesh>
 {cat&&<><mesh position={[-.4,1.75,0]} rotation={[0,0,-.2]}><coneGeometry args={[.28,.62,4]}/><meshStandardMaterial color={color}/></mesh><mesh position={[.4,1.75,0]} rotation={[0,0,.2]}><coneGeometry args={[.28,.62,4]}/><meshStandardMaterial color={color}/></mesh></>}
 {!cat&&<><mesh position={[-.62,1.3,0]} rotation={[0,0,.6]} scale={[.34,.75,.2]}><sphereGeometry args={[.7,18,12]}/><meshStandardMaterial color="#b66e37"/></mesh><mesh position={[.62,1.3,0]} rotation={[0,0,-.6]} scale={[.34,.75,.2]}><sphereGeometry args={[.7,18,12]}/><meshStandardMaterial color="#b66e37"/></mesh></>}
 {[-.25,.25].map((x,i)=><mesh key={i} position={[x,1.28,.66]}><sphereGeometry args={[.08,16,16]}/><meshStandardMaterial color="#292d29"/></mesh>)}<mesh position={[0,1.05,.7]} scale={[1,.65,.6]}><sphereGeometry args={[.13,16,16]}/><meshStandardMaterial color="#312d29"/></mesh>
 {[[-.45,-.62,.25],[.45,-.62,.25]].map((p,i)=><mesh key={i} position={p as [number,number,number]} scale={[.35,.75,.36]}><capsuleGeometry args={[.32,.7,8,16]}/><meshStandardMaterial color={color}/></mesh>)}</group>}
export default function PetScene(){return <Canvas className="scene-canvas" camera={{position:[0,2.2,7],fov:42}} dpr={[1,1.5]} gl={{antialias:true}}><color attach="background" args={["#e7eadc"]}/><ambientLight intensity={1.8}/><directionalLight position={[4,6,5]} intensity={2.2}/><Float speed={1.3} rotationIntensity={.04} floatIntensity={.15}><Animal kind="dog" position={[-1.25,-.5,0]} color="#d9934c"/><Animal kind="cat" position={[1.2,-.55,.2]} color="#586057"/></Float><mesh position={[0,-1.55,0]} rotation={[-Math.PI/2,0,0]}><circleGeometry args={[4,48]}/><meshStandardMaterial color="#f4d8bd"/></mesh><ContactShadows position={[0,-1.48,0]} opacity={.22} scale={8} blur={2.5}/><OrbitControls enableZoom={false} enablePan={false} minAzimuthAngle={-.25} maxAzimuthAngle={.25} minPolarAngle={1.1} maxPolarAngle={1.55}/></Canvas>}
