"use client";
import Image from "next/image";import Link from "next/link";import { Bell,CalendarDays,Heart,LayoutDashboard,MessageCircle,PlusCircle,ShieldCheck } from "lucide-react";import { useState } from "react";import { pets } from "@/lib/data";import PetCard from "@/components/PetCard";import { useFeedback } from "@/components/FeedbackProvider";
const configs={Adopter:{metrics:[["4","Favorites"],["2","Applications"],["1","Upcoming visit"],["75%","Verified"]],title:"Your adoption journey"},Guardian:{metrics:[["3","Active listings"],["8","Applicants"],["2","Meet-ups"],["100%","Verified"]],title:"Your rehoming overview"},Organization:{metrics:[["24","Pets in care"],["16","Applications"],["6","Staff members"],["83%","Placement rate"]],title:"Organization overview"}};
const tabs=[["Overview",LayoutDashboard],["Favorites",Heart],["Messages",MessageCircle],["Appointments",CalendarDays],["Verification",ShieldCheck],["Notifications",Bell]] as const;
export default function Dashboard(){const [role,setRole]=useState<keyof typeof configs>("Adopter");const [tab,setTab]=useState("Overview");const c=configs[role];const {notify}=useFeedback();return <main className="page dashboard-page"><div className="shell"><div className="dashboard-welcome"><div><span className="eyebrow">A calm little command center</span><h2>{c.title}</h2><p>Welcome back, Sam. Here&apos;s what needs your attention.</p></div><select className="input role-select" value={role} onChange={e=>{setRole(e.target.value as keyof typeof configs);setTab("Overview")}} aria-label="Switch demo role"><option>Adopter</option><option>Guardian</option><option>Organization</option></select></div><div className="dashboard-grid"><aside className="sidebar"><b className="sidebar-title">Demo workspace</b>{tabs.map(([label,Icon])=><button type="button" className={tab===label?"active":""} onClick={()=>setTab(label)} key={label}><Icon size={17}/>{label}</button>)}</aside><div>
 {tab==="Overview"&&<><div className="metric-grid">{c.metrics.map(([v,l])=><div className="metric" key={l}><b>{v}</b><span>{l}</span></div>)}</div><div className="panel"><div className="panel-head"><h3>{role==="Adopter"?"Recent applications":"Recent activity"}</h3>{role!=="Adopter"&&<Link href="/listings/new" className="btn btn-primary btn-small"><PlusCircle size={16}/> Add pet</Link>}</div>{[[pets[0],"Under Review","Updated 2 hours ago"],[pets[3],"Meet-and-Greet Scheduled","Saturday · 10:30 AM"],[pets[4],"Draft","Last edited yesterday"]].map(([p,s,t])=>{const pet=p as typeof pets[number];return <div className="application-row" key={pet.id}><Link href={`/pets/${pet.id}`} className="row-pet"><Image src={pet.image} alt="" width={52} height={52}/><span><b>{pet.name}</b><br/><small>{pet.organization}</small></span></Link><span className="status">{String(s)}</span><small>{String(t)}</small></div>})}</div><div className="panel soft-panel"><h3>A gentle reminder</h3><p>Finish your verification when you have a quiet moment. Your saved work will be here.</p><button className="btn btn-dark btn-small" onClick={()=>setTab("Verification")}>Continue verification</button></div></>}
 {tab==="Favorites"&&<div><div className="section-head compact-head"><div><span className="eyebrow">Saved with care</span><h2>Your favorites</h2></div></div><div className="cards">{pets.slice(0,3).map(p=><PetCard key={p.id} pet={p}/>)}</div></div>}
 {tab==="Messages"&&<DashboardList title="Recent conversations" rows={[["Paws & Paths Rescue","Luna's foster sent a new update."],["Second Spring Rescue","Your visit with Bruno is confirmed."]]} action="Open messages" href="/messages"/>}
 {tab==="Appointments"&&<DashboardList title="Upcoming appointments" rows={[["Meet Bruno","Saturday · 10:30 AM · Pasig"],["Phone interview","Tuesday · 4:00 PM · Online"]]} action="Manage schedule" href="/appointments"/>}
 {tab==="Verification"&&<div className="panel"><h3>Verification progress</h3><p>Identity, email, and phone are verified. Your exact documents stay private.</p><div className="progress"><span/></div><button className="btn btn-primary" onClick={()=>notify("Proof-of-address upload is ready in demo mode.")}>Upload proof of address</button></div>}
 {tab==="Notifications"&&<DashboardList title="Notifications" rows={[["Application update","Luna's application moved to Under Review."],["Care reminder","Bruno's meet-and-greet is in three days."],["Profile tip","Add your housing preference to improve matches."]]} action="Mark all as read" onAction={()=>notify("All notifications marked as read.")}/>} </div></div></div></main>}
function DashboardList({title,rows,action,href,onAction}:{title:string;rows:string[][];action:string;href?:string;onAction?:()=>void}){return <div className="panel"><div className="panel-head"><h3>{title}</h3>{href?<Link className="btn btn-primary btn-small" href={href}>{action}</Link>:<button className="btn btn-ghost btn-small" onClick={onAction}>{action}</button>}</div>{rows.map(([name,detail])=><div className="application-row" key={name}><div><b>{name}</b><p className="row-detail">{detail}</p></div><span className="status">Active</span></div>)}</div>}
