"use client";
import { ChevronDown,Search,SlidersHorizontal,X } from "lucide-react";import { useMemo,useState } from "react";import PetCard from "@/components/PetCard";import { pets } from "@/lib/data";
const initial={type:"All",age:"All",location:"All",size:"All",sex:"All",vaccinated:"All",compatibility:"All",special:false,urgent:false};
export default function BrowsePage(){const [query,setQuery]=useState("");const [filters,setFilters]=useState(initial);const [sort,setSort]=useState("Featured");const [advanced,setAdvanced]=useState(false);const [limit,setLimit]=useState(6);const set=(key:keyof typeof initial,value:string|boolean)=>setFilters(f=>({...f,[key]:value}));
 const filtered=useMemo(()=>{let list=pets.filter(p=>(filters.type==="All"||p.type===filters.type)&&(filters.age==="All"||p.ageGroup===filters.age)&&(filters.location==="All"||p.location===filters.location)&&(filters.size==="All"||p.size===filters.size)&&(filters.sex==="All"||p.sex===filters.sex)&&(filters.vaccinated==="All"||(filters.vaccinated==="Yes")===p.vaccinated)&&(filters.compatibility==="All"||p.goodWith.includes(filters.compatibility))&&(!filters.special||Boolean(p.specialNeeds))&&(!filters.urgent||p.urgency==="Urgent")&&`${p.name} ${p.breed} ${p.description}`.toLowerCase().includes(query.toLowerCase()));if(sort==="Name")list=[...list].sort((a,b)=>a.name.localeCompare(b.name));if(sort==="Urgency")list=[...list].sort((a,b)=>a.urgency==="Urgent"?-1:b.urgency==="Urgent"?1:0);return list},[query,filters,sort]);
 const active=Object.entries(filters).filter(([,v])=>v!=="All"&&v!==false).length+(query?1:0);const reset=()=>{setQuery("");setFilters(initial);setLimit(6)};
 return <main className="page browse-page"><div className="shell"><div className="page-title"><span className="eyebrow">Find your companion</span><h1>Good matches start with good stories.</h1><p>Explore pets from verified guardians and welfare groups. Take your time—there&apos;s no pressure here.</p></div><section className="filter-surface" aria-label="Pet filters"><div className="filter-bar"><div className="search-wrap"><Search size={19}/><input className="input" aria-label="Search pets" placeholder="Search by name, breed, or personality…" value={query} onChange={e=>{setQuery(e.target.value);setLimit(6)}}/></div><Filter value={filters.type} label="Animal type" options={["All","Dog","Cat","Rabbit"]} onChange={v=>set("type",v)}/><Filter value={filters.age} label="Age" options={["All","Young","Adult","Senior"]} onChange={v=>set("age",v)}/><Filter value={filters.location} label="Location" options={["All",...new Set(pets.map(p=>p.location))]} onChange={v=>set("location",v)}/></div><button className="advanced-toggle" onClick={()=>setAdvanced(!advanced)} aria-expanded={advanced}><SlidersHorizontal size={17}/> More ways to find the right fit {active>0&&<span>{active}</span>}<ChevronDown size={16}/></button>{advanced&&<div className="advanced-filters"><Filter value={filters.size} label="Size" options={["All","Small","Medium","Large"]} onChange={v=>set("size",v)}/><Filter value={filters.sex} label="Sex" options={["All","Female","Male"]} onChange={v=>set("sex",v)}/><Filter value={filters.vaccinated} label="Vaccinated" options={["All","Yes","No"]} onChange={v=>set("vaccinated",v)}/><Filter value={filters.compatibility} label="Good with" options={["All","Children","Cats","Dogs"]} onChange={v=>set("compatibility",v)}/><label className="check-filter"><input type="checkbox" checked={filters.special} onChange={e=>set("special",e.target.checked)}/> Special-needs pets</label><label className="check-filter"><input type="checkbox" checked={filters.urgent} onChange={e=>set("urgent",e.target.checked)}/> Needs a home soon</label></div>}</section>
 <div className="browse-top"><div><b>{filtered.length} pets</b> <span>waiting for a home</span></div><div className="browse-controls">{active>0&&<button className="btn btn-ghost btn-small" onClick={reset}><X size={15}/> Clear filters</button>}<select className="input sort-select" aria-label="Sort pets" value={sort} onChange={e=>setSort(e.target.value)}><option>Featured</option><option>Name</option><option>Urgency</option></select></div></div><div className="chips" aria-live="polite">{Object.entries(filters).filter(([,v])=>v!=="All"&&v!==false).map(([k,v])=><button className="chip chip-button" key={k} onClick={()=>set(k as keyof typeof initial,typeof v==="boolean"?false:"All")}>{String(v===true?k.replace(/([A-Z])/g," $1"):v)} <X size={12}/></button>)}</div>
 <div className="cards">{filtered.length?filtered.slice(0,limit).map(p=><PetCard key={p.id} pet={p}/>):<div className="empty"><SlidersHorizontal size={38}/><h2>No pets match yet.</h2><p>Try widening your search or clearing a filter.</p><button className="btn btn-primary" onClick={reset}>Clear all filters</button></div>}</div>{filtered.length>limit&&<div className="load-more"><button className="btn btn-dark" onClick={()=>setLimit(x=>x+6)}>Show more gentle faces</button><p>{filtered.length-limit} more pets to meet</p></div>}</div></main>}
function Filter({value,label,options,onChange}:{value:string;label:string;options:Iterable<string>;onChange:(v:string)=>void}){return <select className="input" aria-label={label} value={value} onChange={e=>onChange(e.target.value)}>{[...options].map(x=><option key={x} value={x}>{x==="All"?label:x}</option>)}</select>}
